version: '3.4'
services:
  serialconnector:
    image: serialconnector
    build:
      context: .
      dockerfile: ./.devcontainer/Dockerfile
    volumes: 
      - ${PWD}/workspace:/workspace
      - /var/run/docker.sock:/var/run/docker.sock
    cap_add: 
      - SYS_PTRACE
    security_opt: 
      - seccomp=unconfined
